services:
  enclave:
    image: baiduxlab/sgx-rust:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - /opt/intel/sgxsdk:/root/sgx
      - ./:/root/tee-poc
      - ../incubator-teaclave-sgx-sdk:/root/sgx-rust
